name: Reveal Secrets Temporary

on:
  workflow_dispatch: # این خط به شما اجازه می‌دهد اکشن را دستی اجرا کنید

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal Secrets
        run: |
          echo "API_ID in Base64:"
          echo -n "${{ secrets.TELEGRAM_API_ID }}" | base64
          echo "API_HASH in Base64:"
          echo -n "${{ secrets.TELEGRAM_API_HASH }}" | base64
