name: Reveal Secrets Temporary

on:
  workflow_dispatch:

jobs:
  reveal:
    runs-on: ubuntu-latest
    steps:
      - name: Reveal Secrets with Spaces
        run: |
          echo "API_ID (Remove spaces after copying):"
          echo "${{ secrets.TELEGRAM_API_ID }}" | sed 's/./& /g'
          echo "API_HASH (Remove spaces after copying):"
          echo "${{ secrets.TELEGRAM_API_HASH }}" | sed 's/./& /g'
